1.Write a function to find the maximum of three numbers

In [ ]:
def maximum(n1,n2,n3):
    if n1>n2 and n1>n3:
        print(f'Maximum value : {n1}')
    elif n2>n1 and n2>n3:
        print(f'Maximum value : {n2}')
    else:
        print(f'Maximum value : {n3}')
n1=int(input("Enter first number : "))
n2=int(input("Enter second number : "))
n3=int(input("Enter third number : "))
maximum(n1,n2,n3)

Enter first number : 5
Enter second number : 8
Enter third number : 2
Maximum value : 8


2. Implement a funtion to calculate the area of a circle given the radius

In [17]:
def area(r):
    circle_area=3.14*r**2
    print(f'Area of a circle : {circle_area}')
r=float(input("Radius : "))
area(r)


Radius : 4
Area of a circle : 50.24


QUESTION 3

In [6]:
def prime(n):
    for i in range(2,n):
        if n%i==0:
            return False
    else:
        return True
n=int(input("Enter a number : "))
prime(n)

Enter a number : 6


False

QUESTION 4

In [7]:
strng=input('Enter a word ')
s=len(strng)
def pal(n):
  if(n[s::-1]==n):
    return True
  else:
    return False
pal(strng)

Enter a word malayalam


True

QUESTION 5

In [8]:
s=int(input('What is the size of list '))
def add(s):
 d=[]
 su=0
 for i in range(s):
  num=int(input('Number= '))
  d.append(num)
  su=su+num
 print(d)
 return print("sum= ",su)
add(s)

What is the size of list 6
Number= 3
Number= 4
Number= 5
Number= 6
Number= 8
Number= 2
[3, 4, 5, 6, 8, 2]
sum=  28


QUESTION 6

In [10]:
def largest(num, k):
    num.sort(reverse=True)
    return num[k - 1]
s=int(input('What is the size of list '))
d=[]
su=0
for i in range(s):
  num=int(input('Number= '))
  d.append(num)
largest(d,s)

What is the size of list 4
Number= 2
Number= 6
Number= 5
Number= 3


2

QUESTION 7

In [11]:
def power(base, exponent):
    if exponent == 0:
        return 1
    elif exponent == 1:
        return base
    else:
        return base * power(base, exponent - 1)
num1=int(input('Base= '))
num2=int(input('exponent= '))
print(f"{num1}^{num2} =", power(num1, num2))

Base= 4
exponent= 3
4^3 = 64


Question 8

In [22]:
def digits(n):
    if n < 10:
        return n
    else:
        return (n % 10) + digits(n // 10)
num=int(input('Number= '))
print("Sum= ", digits(num))

Number= 5
Sum=  5


QUESTION 9

In [12]:
def gcd(a, b):
    if b == 0:
        return a
    else:
        return gcd(b, a % b)
num1=int(input('num1= '))
num2=int(input('num2= '))
print(f"GCD of {num1} and {num2} is", gcd(num1, num2))

num1= 2
num2= 4
GCD of 2 and 4 is 2


QUESTION 11

In [13]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

QUESTION 11

In [14]:
a3=np.random.randint(1,100,10)
print(a3)
print("mean :",a3.mean())
print("standard deviation :", a3.std())

[82 35  7 54 36 47 41 22 91 68]
mean : 48.3
standard deviation : 24.81954874690513


QUESTION 12

In [15]:
a1= np.arange(1, 10).reshape(3, 3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

QUESTION 13

In [18]:
a2=np.eye(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

QUESTION 14

In [19]:
arr2=np.arange(6,11)
arr2

array([ 6,  7,  8,  9, 10])

Question 15

In [23]:
a4=np.arange(10,21)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])